server:
  port: 6607
spring:
  application:
    name: car-service
  config:
   import: optional:configserver:http://localhost:6602
cloud:
  config:
    fail-fast: true 



management:
  endpoints:
    web:
      exposure:
        include: "*"